/** HTS Chapter (first 2 digits) to short title for display. Subset of US HTS. */
export const HTS_CHAPTER_TITLES: Record<string, string> = {
  "01": "Live animals",
  "02": "Meat and edible meat offal",
  "03": "Fish and crustaceans, molluscs",
  "04": "Dairy produce; birds' eggs; natural honey",
  "05": "Products of animal origin, nesoi",
  "06": "Live trees and other plants",
  "07": "Edible vegetables and certain roots and tubers",
  "08": "Edible fruit and nuts",
  "09": "Coffee, tea, mate and spices",
  "10": "Cereals",
  "11": "Products of the milling industry",
  "12": "Oil seeds and oleaginous fruits",
  "13": "Lac; gums, resins and other vegetable saps",
  "14": "Vegetable plaiting materials",
  "15": "Animal or vegetable fats and oils",
  "16": "Preparations of meat, fish or crustaceans",
  "17": "Sugars and sugar confectionery",
  "18": "Cocoa and cocoa preparations",
  "19": "Preparations of cereals, flour, starch or milk",
  "20": "Preparations of vegetables, fruit, nuts",
  "21": "Miscellaneous edible preparations",
  "22": "Beverages, spirits and vinegar",
  "23": "Residues and waste from the food industry",
  "24": "Tobacco and manufactured tobacco substitutes",
  "25": "Salt; sulfur; earths and stone; plastering materials",
  "26": "Ores, slag and ash",
  "27": "Mineral fuels, oils and distillation products",
  "28": "Products of the chemical or allied industries",
  "29": "Organic chemicals",
  "30": "Pharmaceutical products",
  "31": "Fertilizers",
  "32": "Tanning or dyeing extracts; dyes, paints",
  "33": "Essential oils and resinoids; perfumery",
  "34": "Soap, organic surface-active agents; washing preparations",
  "35": "Albuminoidal substances; modified starches; glues",
  "36": "Explosives; pyrotechnic products; matches",
  "37": "Photographic or cinematographic goods",
  "38": "Miscellaneous chemical products",
  "39": "Plastics and articles thereof",
  "40": "Rubber and articles thereof",
  "41": "Raw hides and skins (other than furskins) and leather",
  "42": "Articles of leather; saddlery and harness",
  "43": "Furskins and artificial fur; manufactures thereof",
  "44": "Wood and articles of wood",
  "45": "Cork and articles of cork",
  "46": "Manufactures of straw, of esparto or of other plaiting materials",
  "47": "Pulp of wood or of other fibrous cellulosic material",
  "48": "Paper and paperboard; articles of paper pulp",
  "49": "Printed books, newspapers, pictures and other products",
  "50": "Silk",
  "51": "Wool, fine or coarse animal hair",
  "52": "Cotton",
  "53": "Other vegetable textile fibers",
  "54": "Man-made filaments",
  "55": "Man-made staple fibers",
  "56": "Wadding, felt and nonwovens; special yarns",
  "57": "Carpets and other textile floor coverings",
  "58": "Special woven fabrics; tufted textile fabrics",
  "59": "Impregnated, coated, covered or laminated textile fabrics",
  "60": "Knitted or crocheted fabrics",
  "61": "Articles of apparel and clothing accessories, knitted",
  "62": "Articles of apparel and clothing accessories, not knitted",
  "63": "Other made up textile articles",
  "64": "Footwear, gaiters and the like",
  "65": "Headgear and parts thereof",
  "66": "Umbrellas, walking sticks, seat-sticks, whips",
  "67": "Prepared feathers and down and articles thereof",
  "68": "Articles of stone, plaster, cement, asbestos, mica",
  "69": "Ceramic products",
  "70": "Glass and glassware",
  "71": "Natural or cultured pearls, precious or semi-precious stones",
  "72": "Iron and steel",
  "73": "Articles of iron or steel",
  "74": "Copper and articles thereof",
  "75": "Nickel and articles thereof",
  "76": "Aluminum and articles thereof",
  "77": "Reserved for future use",
  "78": "Lead and articles thereof",
  "79": "Zinc and articles thereof",
  "80": "Tin and articles thereof",
  "81": "Other base metals; cermets; articles thereof",
  "82": "Tools, implements, cutlery, spoons and forks, of base metal",
  "83": "Miscellaneous articles of base metal",
  "84": "Nuclear reactors, boilers, machinery and mechanical appliances",
  "85": "Electrical machinery and equipment and parts thereof",
  "86": "Railway or tramway locomotives, rolling-stock",
  "87": "Vehicles other than railway or tramway rolling-stock",
  "88": "Aircraft, spacecraft, and parts thereof",
  "89": "Ships, boats and floating structures",
  "90": "Optical, photographic, cinematographic, measuring, medical instruments",
  "91": "Clocks and watches and parts thereof",
  "92": "Musical instruments; parts and accessories thereof",
  "93": "Arms and ammunition; parts and accessories thereof",
  "94": "Furniture; bedding, mattresses; lamps and lighting fittings",
  "95": "Toys, games and sports equipment; parts and accessories thereof",
  "96": "Miscellaneous manufactured articles",
  "97": "Works of art, collectors' pieces and antiques",
};

export const getChapterTitle = (slug: string): string | null => {
  const ch = slug.slice(0, 2);
  return HTS_CHAPTER_TITLES[ch] ?? null;
};

/** US HTS chapter codes (01–97) for browse-by-chapter in numeric order; no locale. */
export const getUsHtsChapterCodes = (): string[] =>
  Object.keys(HTS_CHAPTER_TITLES).sort(
    (a, b) => parseInt(a, 10) - parseInt(b, 10)
  );
